//==
//Scar20
//=
//Material
resource.AddFile("materials/models/weapons/v_models/go_scar/scope_normal.vtf")
resource.AddFile("materials/models/weapons/v_models/go_scar/scope_scar20.vtf")
resource.AddFile("materials/models/weapons/v_models/go_scar/scope_scar20.vmt")
resource.AddFile("materials/models/weapons/v_models/go_scar/snip_scar20.vmt")
resource.AddFile("materials/models/weapons/v_models/go_scar/snip_scar20.vtf")
resource.AddFile("materials/models/weapons/v_models/go_scar/snip_scar20_exponent.vtf")
//Model
resource.AddFile("models/weapons/v_snip_scar20.mdl")
resource.AddFile("models/weapons/v_snip_scar20.sw.vtx")
resource.AddFile("models/weapons/w_snip_scar20.mdl")
resource.AddFile("models/weapons/w_snip_scar20.sw.vtx")
//Sound
resource.AddFile("sound/scar20_unsil-1.wav")